#!/usr/bin/env bash
set -euox pipefail
shopt -s globstar

cd "$(dirname "$0")"

# For JS grammars
node -r @danielx/hera/register ./hera-standard/use.mjs
node -r @danielx/hera/register ./hera-standard/use.cjs

# For TS grammars
node -r @danielx/hera/register/tsc ./tsc-standard/use.mjs
node -r @danielx/hera/register/tsc ./tsc-standard/use.cjs

# For JS grammars with custom Hera options
node -r ./custom-hera/register.js ./custom-hera/use.mjs
node -r ./custom-hera/register.js ./custom-hera/use.cjs

# For TS grammars with custom compiler options
node -r ./custom-tsc/register.js ./custom-tsc/use.mjs
node -r ./custom-tsc/register.js ./custom-tsc/use.cjs

# For custom transforms after Hera compile
node -r ./custom-transform/register.js ./custom-transform/use.mjs
node -r ./custom-transform/register.js ./custom-transform/use.cjs

